### PR TITLE
CDB changes

### PR DESCRIPTION
**Pull request by davidkurtz**
This set of changes allows EDB360 to report on all the pluggable databases in a container by switching most of the queries to use CDB% views instead of DBA% views.  New skip variables remove CON_ID.  The name of the PDB is obtained by outer joining to V$CONTAINTERS.
Also includes corrections to skip variables to ensure @@ is before &&skip variables.

### CODE REVIEW

**Comment by mauropagano** [comment]
Few things:

- Thanks for doing the work, I really really appreciate it. I think this is great.

- There are a few conflicts, I think it's because the changes are on top of code branched a bit ago. We might be able to just rebase but I'm not 100% sure

- It's quite a large change so I pulled in @carlos-sierra for the review, I'd like to add @abelmacias too since he made several recent changes

- I don't have a CDV handy to test, any chance you do and can send me an edb360 from it? I just want to go through the pages and confirm so problems

Just to be clear, I'm not too worried about merging (assuming we resolve conflicts, of course) given we would merge into "unstable" but we would still need significant test before making a release off of it

**Comment by davidkurtz** [comment]
The files are too big to e-mail.  So I have generated EDB360s and put the
zip files on my google drive.  You shouldn't require a log-in.
https://drive.google.com/drive/folders/1Ddz0SRXdMVAPMEUw8KLqz9r4G5VnJIOz?usp=sharing

* edb360_247358_598024_20200525_1516.zip - on 19c6.  In root container
* edb360_247358_598024_20200525_1529.zip - on same 19c6 database, but in a
PDB.

I think most of the conflicts are from the previous merge request that
changed all the skip variables.  I was careful to merge my changes into the
current version of SQLDB360.


regards
_________________________
David Kurtz

**Comment by mauropagano** [comment]
I'm working through the conflicts and most of them are trivial, not sure which one is correct here
From moat369_fc_oracle_version.sql
```
358 select
359 <<<<<<< HEAD
360 decode('&&is_cdb.','Y','','N','--') skip_cdb,
361 decode('&&is_cdb.','Y','--','N','') skip_noncdb
362 =======
363 decode('&&is_cdb.','Y','','N','--') skip_noncdb,
364 decode('&&is_cdb.','Y','--','N','') skip_cdb
365 >>>>>>> 0e6c9b4f409b68b8b4319d90cd44c916d57a7fe8
366 from dual;
```

**Comment by mauropagano** [comment]
The vast majority of the conflicts are caused by variables that swapped position, like this in edb360_3h_sessions.sql

```
 756 <<<<<<< HEAD
 757 &&skip_ver_le_10.@@edb360_9a_pre_one.sql
 758 =======
 759 @@&&skip_ver_le_10.edb360_9a_pre_one.sql
 760 >>>>>>> 0e6c9b4f409b68b8b4319d90cd44c916d57a7fe8
```

the second one is right imho, do we agree? I think what happened is the problem was in PR #62 (e.g. [here](https://github.com/davidkurtz/sqldb360/blob/06be28561f061378e4bd765156dac79a9a0b2f87/sql/edb360_3h_sessions.sql)) and we missed and now you corrected it ([here](https://github.com/sqldb360/sqldb360/blob/0e6c9b4f409b68b8b4319d90cd44c916d57a7fe8/sql/edb360_3h_sessions.sql)). 
Does it sound like a possibility?

**Comment by davidkurtz** [comment]
Agreed.  Jorge and I had a discussion about this.  The @@ should come
before the &&

regards
_________________________
David Kurtz

**Comment by davidkurtz** [comment]
This was a bugfix in Moat369.
lines 363-364 are correct.  Lines 360-361 are wrong.

regards
_________________________
David Kurtz

**Comment by mauropagano** [comment]
Got almost all of the simple ones, should be able to get all of them in the next couple days.
I would like for you to retest after that to make sure I didn't break something while fixing conflicts

**Comment by davidkurtz** [comment]
Absolutely yes, and I want to bring my fork back in line with the base
repository.

**Comment by mauropagano** [comment]
Time for testing, I merged it meanwhile. Any new fix we can make a new PR

**Pull request merged**
